### ISSUE TITLE
Неконсистентная идентация, мы учим везде 4 пробела.

### ISSUE THREAD

**Issue by denis-trofimov** [nemcev/lesson1#1]
https://github.com/nemcev/lesson1/blob/4de06fe80c285098a18ef6ce9061b65b641f705b/inwork.py#L6

**Comment by nemcev** [comment]
это как?

**Comment by denis-trofimov** [comment]
```
    if max_discount > 99:
            raise ValueError('Максимальная скидка не может быть больше 99%')
```
if на 4 пробела, потом 8 пробелов или двойной таб, а должно быть 4 пробела
